name: StatsPush

on:
  push:
    branches: [main]

jobs:
  build:
    if: github.repository == 'jomitame/actions-stats' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: SP Checkout Repo
        uses: actions/checkout@v4

      - name: SP Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: SP Run Script
        run: python ./retos/stats.py

      - name: SP Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Stats
          commit_user_name: jomitame [GitHub Actions]
          commit_user_email: jomitame@gmail.com
          commit_author: jomitame <jomitame@gmail.com>