name: StatsCron

on:
  schedule:
    - cron: '30 10 * * *'

jobs:
  build:
    if: github.repository == 'jomitame/actions-stats' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: SC Checkout Repo
        uses: actions/checkout@v4

      - name: SC Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: SC Run Script
        run: python ./retos/stats.py

      - name: SC Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Stats
          commit_user_name: jomitame [GitHub Actions]
          commit_user_email: jomitame@gmail.com
          commit_author: jomitame jomitame <jomitame@gmail.com>